---
title: Mouse.isPressed()
---




= Mouse.isPressed()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Перевіряє поточний стан усіх кнопок миші та повідомляє, чи натиснуті вони чи ні.
[%hardbreaks]


[float]
=== Syntax
`Mouse.isPressed();` +
`Mouse.isPressed(button);`

[float]
=== Parameters
Якщо значення не передано, перевіряється стан лівої кнопки миші.

`button`: яку кнопку миші перевіряти. Дозволені типи даних: `char`.

* `MOUSE_LEFT (за замовчуванням)`
* `MOUSE_RIGHT`
* `MOUSE_MIDDLE`


[float]
=== Returns
Повідомляє, чи натиснута кнопка чи ні. Тип даних: `bool`.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Опишіть, про що йдеться у прикладі коду, та додайте відповідний код  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
#include <Mouse.h>

void setup() {
  //Перемикач, який розпочне натискання миші
  pinMode(2, INPUT);
  //Перемикач, який завершить натискання миші
  pinMode(3, INPUT);
  //Почати послідовний зв'язок з комп'ютером
  Serial.begin(9600);
  //ініціалізувати бібліотеку Mouse
  Mouse.begin();
}

void loop() {
  //змінна для перевірки стану кнопки
  int mouseState = 0;
  //якщо перемикач, підключений до контакту 2, замкнуто, натиснути та утримувати ліву кнопку миші та зберегти стан у змінну
  if (digitalRead(2) == HIGH) {
    Mouse.press();
    mouseState = Mouse.isPressed();
  }
  //якщо перемикач, підключений до контакту 3, замкнуто, відпустити ліву кнопку миші та зберегти стан у змінну
  if (digitalRead(3) == HIGH) {
    Mouse.release();
    mouseState = Mouse.isPressed();
  }
  //вивести поточний стан кнопки миші
  Serial.println(mouseState);
  delay(10);
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE# link:../mouseclick[Mouse.click()]
* #LANGUAGE# link:../mouseend[Mouse.end()]
* #LANGUAGE# link:../mousemove[Mouse.move()]
* #LANGUAGE# link:../mousepress[Mouse.press()]
* #LANGUAGE# link:../mouserelease[Mouse.release()]

--
// SEE ALSO SECTION ENDS
