---
title: array
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

= array

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Масив — це набір даних, доступ до яких здійснюється за допомогою порядкового номера (індексу). Масиви в мові програмування C++, на якій пишуться скетчі Arduino, можуть бути складними, але використання простих масивів є відносно простим та дає змогу створювати досить складні програми та скрипти.

[float]
=== Оголошення масиву

Усі наведені нижче методи є дійсними способами створення (оголошення) масиву.
[source,arduino]
----
  // Оголосити масив заданої довжини без ініціалізації значень:
  int myInts[6];

  // Оголосити масив не вказуючи його розмір та ініціалізувати його значення:
  int myPins[] = {2, 4, 8, 3, 6, 4};

  // Оголосити масив заданої довжини та ініціалізувати його значення:
  int mySensVals[5] = {2, 4, -8, 3, 2};

  // Оголосити масив символів (рядок) та ініціалізувати його значення:
  char message[6] = "hello";
----

[%hardbreaks]

[float]
=== Доступ до елементів масиву
Масиви індексуються з нуля, тобто, звертаючись до наведеної вище ініціалізації масиву, перший елемент масиву ЗАВЖДИ знаходиться за індексом 0, отже

`mySensVals[0] == 2, mySensVals[1] == 4,` і так далі.

Це також означає, що в масиві з десяти елементів дев'ятий індекс — це останній елемент. Отже:

[source,arduino]
----
int myArray[10]={9, 3, 2, 4, 3, 2, 7, 8, 9, 11};
// myArray[9]    дорівнює 11
// myArray[10]   не існує
----
З цієї причини ви повинні бути обережними при доступі до елементів масивів. Доступ за межами масиву (використання номера індексу, більшого за оголошений розмір масиву мінус 1) є читанням з пам'яті, яка використовується для інших цілей. Читання з цих місць, ймовірно, не дасть нічого, крім недійсних даних. Запис у випадкові ділянки пам'яті, безумовно, є поганою ідеєю і часто може призвести до неприємних наслідків, таких як збої, некоретні результати або несправності програми взагалі. Цю помилку також може бути важко відстежити.
[%hardbreaks]

На відміну від BASIC або JAVA, компілятор C++ не перевіряє, чи знаходиться доступ до масиву в межах оголошеного розміру масиву. Нажаль.
[%hardbreaks]

[float]
=== Зміна значень масиву:
Щоб присвоїти нове значення елементу масиву:
`mySensVals[0] = 10;`
[%hardbreaks]

[float]
=== Отримання значень з масиву:
Щоб отримати значення з масиву:
`x = mySensVals[4];`
[%hardbreaks]

[float]
=== Массиви та цикли
Масиви часто обробляються всередині циклів `for`, де лічильник циклу використовується як індекс для кожного елемента масиву. Наприклад, щоб надрукувати елементи масиву через послідовний порт, ви можете зробити щось подібне:

[source,arduino]
----
for (byte i = 0; i < 5; i = i + 1) {
  Serial.println(myPins[i]);
}
----
[%hardbreaks]

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Приклад коду
Для отримання повного лістингу коду програми, яка демонструє використання масивів, дивіться тут (https://docs.arduino.cc/built-in-examples/control-structures/Arrays[Як використовувати масиви]) з (https://docs.arduino.cc/built-in-examples[Вбудованих прикладів]).

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Додатково

[role="language"]
* #LANGUAGE# link:../../utilities/progmem[PROGMEM]


--
// SEE ALSO SECTION ENDS
