---
title: float
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---





= float


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Тип даних для чисел з плаваючою комою, тобто чисел, які мають десяткову крапку. Числа з плаваючою комою часто використовуються для наближення аналогових і неперервних значень, оскільки вони мають більшу роздільну здатність, ніж цілі числа. Числа з плаваючою комою можуть бути як великими до 3.4028235E+38, так і малими до -3.4028235E+38. Вони зберігаються у вигляді 32 біт (4 байт) інформації.


[%hardbreaks]

[float]
=== Синтаксис
`float var = val;`

[float]
=== Параметри
`var`: ім'я змінної. +
`val`: значення, яке ви присвоюєте цій змінній.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Приклад коду
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
float myfloat;
float sensorCalbrate = 1.117;

int x;
int y;
float z;

x = 1;
y = x / 2;          // y now contains 0, ints can't hold fractions
z = (float)x / 2.0; // z now contains .5 (you have to use 2.0, not 2)
----
[%hardbreaks]

[float]
=== Примітки та попередження
Якщо ви виконуєте математичні операції з числами `float`, вам потрібно додати десяткову крапку, інакше вони розглядатимуться як `int`. Дивіться сторінку link:../../constants/floatingpointconstants[Константи з плаваючою комою] для отримання деталей.

Тип даних float має точність лише 6-7 десяткових цифр. Це означає загальну кількість цифр, а не кількість праворуч від десяткової крапки. На відміну від інших платформ, де можна отримати більшу точність за допомогою `double` (наприклад, до 15 цифр), на Arduino `double` має той самий розмір, що й `float`.

Числа з плаваючою комою не є точними і можуть давати дивні результати при їх порівнянні. Наприклад, 9.0 / 0.3 може не зовсім дорівнювати 30.0. Натомість слід перевіряти, чи абсолютне значення різниці між числами менше за якесь дуже мале число.

Перетворення математики чисел з плаваючою комою в цілочисельну математику призводить до відсікання дробової частини:
[source,arduino]
----
float x = 2.9; // A float type variable
int y = x;  // 2
----

Якщо натомість ви хочете округлити число під час процесу перетворення, вам потрібно додати `0.5`:
[source,arduino]
----
float x = 2.9;
int y = x + 0.5;  // 3
----
або використати функцію `round()`:
[source,arduino]
----
float x = 2.9;
int y = round(x);  // 3
----

Математичні обчислення з плаваючою комою також є значно повільнішими за цілочисельні обчислення, тому їх слід уникати, якщо, наприклад, цикл має виконуватися з максимальною швидкістю для функцій, критичних щодо часу виконання. Програмісти часто докладають великих зусиль, щоб перетворити обчислення з плаваючою комою на цілочисельні для збільшення швидкості.

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION STARTS
[#see_also]
--

[%hardbreaks]
[float]
=== See also

[role="language"]

--
// SEE ALSO SECTION ENDS
