---
title: int
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

= int


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Ціле число (int) – це один з основних типів даних для зберігання чисел.

На платах Arduino Uno (та інших на базі ATmega) `int` зберігає 16-бітне (2-байтове) значення. Це дає діапазон від -32,768 до 32,767 (мінімальне значення -2^15 та максимальне значення (2^15) - 1).
На платах Arduino Due та платах на базі SAMD (наприклад, MKR1000 і Zero) `int` зберігає 32-бітне (4-байтове) значення. Це дає діапазон від -2,147,483,648 до 2,147,483,647 (мінімальне значення -2^31 та максимальне значення (2^31) - 1).

Змінні `int` зберігають від'ємні числа за допомогою методу (http://en.wikipedia.org/wiki/2%27s_complement[додаткового коду]). Старший біт, який іноді називають "знаковим" бітом, позначає число як від'ємне. Усі інші біти інвертуються, після чого до них додається 1.

Arduino самостійно обробляє від'ємні числа, тому арифметичні операції виконуються прозоро і очікувано. Натомість може виникнути несподіване ускладнення під час використання оператора link:../../../structure/bitwise-operators/bitshiftright[побітового зсуву вправо] (`>>`).
[%hardbreaks]


[float]
=== Синтаксис
`int var = val;`


[float]
=== Параметри
`var`: ім'я змінної. +
`val`: значення, яке ви присвоюєте цій змінній.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Приклад коду
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Цей код створює ціле число з назвою 'countUp', яке спочатку дорівнює 0 (нулю). З кожним циклом змінна збільшується на 1 (один), відображаючись у моніторі послідовного порту.

[source,arduino]
----
int countUp = 0;            //створює ціле число з назвою 'countUp'

void setup() {
  Serial.begin(9600);       // відображаючись у моніторі послідовного порту
}

void loop() {
  countUp++;                // змінна збільшується на 1 (один) з кожною ітерацією циклу
  Serial.println(countUp);  // відображаючись у моніторі послідовного порту
  delay(1000);
}
----
[%hardbreaks]

[float]
=== Нотатки
Коли змінні перевищують свою максимальну або мінімальну місткість, вони _переповнюються_. Результат переповнення є непередбачуваним, тому цього слід уникати. Типовим симптомом переповнення є "перескок" змінної від максимального значення до мінімального або навпаки, але це не завжди так. Якщо вам потрібна подібна поведінка, тоді використовуйте `link:../unsignedint[unsigned int]`.


--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Додатково

[role="language"]
* #LANGUAGE# link:../../constants/integerconstants[Цілочисельні Константи] +

--
// SEE ALSO SECTION ENDS
