---
title: "String()"
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

= String()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Конструює екземпляр класу String. Існує кілька версій, які створюють рядки з різних типів даних (тобто форматують їх як послідовності символів), зокрема:

* стала послідовність символів, у подвійних лапках (тобто масив char)
* одиночний сталий символ, у одинарних лапках
* ще один екземпляр об'єкта String
* стале ціле число (int або long)
* стале ціле число (int або long), використовуючи вказану систему числення
* змінна цілого числа (int або long)
* змінна цілого числа (int або long), використовуючи вказану систему числення
* число з плаваючою комою (float або double), використовуючи вказану кількість десяткових знаків

Створення рядка з числа призводить до появи рядка, який містить ASCII-представлення цього числа. Значенням за замовчуванням є десяткова система числення, тому
[source,arduino]
----
String thisString = String(13);
----
дає вам рядок "13". Однак ви можете використовувати й інші системи. Наприклад,


[source,arduino]
----
String thisString = String(13, HEX);
----

дає вам рядок "d", який є шістнадцятковим представленням десяткового значення 13. Або, якщо ви віддаєте перевагу двійковій,

[source,arduino]
----
String thisString = String(13, BIN);
----

дає вам рядок "1101", який є двійковим представленням 13.
[%hardbreaks]


[float]
=== Syntax
`String(val)` +
`String(val, base)` +
`String(val, decimalPlaces)`


[float]
=== Parameters
`val`: змінна для форматування як String. Допустимі типи даних: string, char, byte, int, long, unsigned int, unsigned long, float, double. +
`base`: (необов'язково) система числення, у якій слід форматувати ціле значення. +
`decimalPlaces`: *тільки якщо val має тип float або double*. Бажана кількість десяткових знаків.


[float]
=== Returns
Екземпляр класу String.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
Усі наведені нижче оголошення є дійсними для Strings.
[source,arduino]
----
String stringOne = "Hello String";                    // using a constant String
String stringOne = String('a');                       // converting a constant char into a String
String stringTwo = String("This is a string");        // converting a constant string into a String object
String stringOne = String(stringTwo + " with more");  // concatenating two strings
String stringOne = String(13);                        // using a constant integer
String stringOne = String(analogRead(0), DEC);        // using an int and a base
String stringOne = String(45, HEX);                   // using an int and a base (hexadecimal)
String stringOne = String(255, BIN);                  // using an int and a base (binary)
String stringOne = String(millis(), DEC);             // using a long and a base
String stringOne = String(5.698, 3);                  // using a float and the decimal places
----

--
// HOW TO USE SECTION ENDS


[float]
=== Functions

[role="language"]
* #LANGUAGE# link:../string/functions/charat[charAt()]
* #LANGUAGE# link:../string/functions/compareto[compareTo()]
* #LANGUAGE# link:../string/functions/concat[concat()]
* #LANGUAGE# link:../string/functions/c_str[c_str()]
* #LANGUAGE# link:../string/functions/endswith[endsWith()]
* #LANGUAGE# link:../string/functions/equals[equals()]
* #LANGUAGE# link:../string/functions/equalsignorecase[equalsIgnoreCase()]
* #LANGUAGE# link:../string/functions/getbytes[getBytes()]
* #LANGUAGE# link:../string/functions/indexof[indexOf()]
* #LANGUAGE# link:../string/functions/lastindexof[lastIndexOf()]
* #LANGUAGE# link:../string/functions/length[length()]
* #LANGUAGE# link:../string/functions/remove[remove()]
* #LANGUAGE# link:../string/functions/replace[replace()]
* #LANGUAGE# link:../string/functions/reserve[reserve()]
* #LANGUAGE# link:../string/functions/setcharat[setCharAt()]
* #LANGUAGE# link:../string/functions/startswith[startsWith()]
* #LANGUAGE# link:../string/functions/substring[substring()]
* #LANGUAGE# link:../string/functions/tochararray[toCharArray()]
* #LANGUAGE# link:../string/functions/todouble[toDouble()]
* #LANGUAGE# link:../string/functions/toint[toInt()]
* #LANGUAGE# link:../string/functions/tofloat[toFloat()]
* #LANGUAGE# link:../string/functions/tolowercase[toLowerCase()]
* #LANGUAGE# link:../string/functions/touppercase[toUpperCase()]
* #LANGUAGE# link:../string/functions/trim[trim()]

[float]
=== Operators

[role="language"]
* #LANGUAGE# link:../string/operators/elementaccess[[\] (element access)]
* #LANGUAGE# link:../string/operators/concatenation[+ (concatenation)]
* #LANGUAGE# link:../string/operators/append[+= (append)]
* #LANGUAGE# link:../string/operators/comparison[== (comparison)]
* #LANGUAGE# link:../string/operators/greaterthan[> (greater than)]
* #LANGUAGE# link:../string/operators/greaterthanorequalto[>= (greater than or equal to)]
* #LANGUAGE# link:../string/operators/lessthan[< (less than)]
* #LANGUAGE# link:../string/operators/lessthanorequalto[\<= (less than or equal to)]
* #LANGUAGE# link:../string/operators/differentfrom[!= (different from)]

[role="example"]
* #EXAMPLE# https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[String Tutorials^]


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== See also

[role="language"]

--
// SEE ALSO SECTION ENDS
