---
title: string
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

= string

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Текстові рядки можна представити двома способами. Ви можете використовувати тип даних String або створити рядок із масиву типу char, який закінчується нульовим символом. На цій сторінці описано останній метод. Для отримання детальнішої інформації про об'єкт String, який надає більше функціональності за рахунок більшого обсягу пам'яті, дивіться сторінку link:../stringobject[об'єкт String].
[%hardbreaks]

[float]
=== Syntax
Усі наведені нижче оголошення є дійсними для рядків.

`char Str1[15];` +
`char Str2[8] = {'a', 'r', 'd', 'u', 'i', 'n', 'o'};` +
`char Str3[8] = {'a', 'r', 'd', 'u', 'i', 'n', 'o', '\0'};` +
`char Str4[] = "arduino";` +
`char Str5[8] = "arduino";` +
`char Str6[15] = "arduino";`

*Можливості оголошення рядків*

* Оголосити масив chars без його ініціалізації, як у Str1
* Оголосити масив chars (з одним додатковим символом), і компілятор додасть необхідний нульовий символ, як у Str2
* Явно додати нульовий символ, Str3
* Ініціалізувати рядковою константою в лапках; компілятор визначить розмір масиву відповідно до рядкової константи та нульового символу завершення, Str4
* Ініціалізувати масив з явним розміром і рядковою константою, Str5
* Ініціалізувати масив, залишивши додатковий простір для більшого рядка, Str6

*Нульове завершення*

Зазвичай рядки закінчуються нульовим символом (ASCII-код 0). Це дозволяє функціям (наприклад, `link:../../../functions/communication/serial/print[Serial.print()]`) визначати, де закінчується рядок. Інакше вони б продовжували читати наступні байти пам'яті, які насправді не є частиною рядка.

Це означає, що ваш рядок повинен мати місце для одного додаткового символу порівняно з текстом, який ви хочете в ньому зберігати. Ось чому Str2 і Str5 повинні мати вісім символів, хоча "arduino" має лише сім - остання позиція автоматично заповнюється нульовим символом. Розмір Str4 автоматично встановлюється у вісім символів, з одним додатковим для нуля. У Str3 ми явно включили нульовий символ (записаний як '\0') самостійно.

Зауважте, що можливо мати рядок без кінцевого нульового символу (наприклад, якби ви вказали довжину Str2 як сім замість восьми). Це порушить роботу більшості функцій, які використовують рядки, тому вам не слід робити це навмисно. Якщо ви помітили, що щось поводиться дивно (працює з символами, яких немає в рядку), однак, це може бути проблемою.

*Одинарні чи подвійні лапки?*

Рядки завжди визначаються в подвійних лапках ("Abc"), а символи завжди визначаються в одинарних лапках ('A').

*Перенесення довгих рядків*

Ви можете переносити довгі рядки так:

[source,arduino]
----
char myString[] = "This is the first line"
" this is the second line"
" etcetera";
----

*Масиви рядків*

Часто зручно, працюючи з великими обсягами тексту, наприклад, у проекті з LCD-дисплеєм, налаштувати масив рядків. Оскільки рядки самі по собі є масивами, це насправді є прикладом двовимірного масиву.

У наведеному нижче коді зірочка після типу даних `link:../char[char]` "`char*`" вказує на те, що це масив "`вказівників`" (pointers). Всі імена масивів насправді є вказівниками, тому це необхідно для створення масиву масивів. Вказівники є однією з більш складних частин C++ для розуміння початківцями, але не обов'язково розуміти вказівники в деталях, щоб ефективно використовувати їх тут.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Опишіть, про що приклад коду, і додайте відповідний код   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
char *myStrings[] = {"This is string 1", "This is string 2", "This is string 3",
                     "This is string 4", "This is string 5", "This is string 6"
                    };

void setup() {
  Serial.begin(9600);
}

void loop() {
  for (int i = 0; i < 6; i++) {
    Serial.println(myStrings[i]);
    delay(500);
  }
}
----


--
// HOW TO USE SECTION ENDS

// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE# link:../../utilities/progmem[PROGMEM]

--
// SEE ALSO SECTION ENDS
