---
title: unsigned int
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---

= unsigned int

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
На платах Uno та інших на базі ATMEGA беззнакові цілі числа `unsigned int` подібні до `int` тим, що вони зберігають 2-байтове значення. Однак замість того, щоб зберігати від'ємні числа, вони зберігають лише додатні значення, забезпечуючи корисний діапазон від 0 до 65 535 ((2^16) - 1).

Різниця між беззнаковими цілими `unsigned int` і знаковими цілими `int` полягає в інтерпретації старшого біта, який іноді називають "знаковим" бітом. У типі `int` Arduino (який має знак), якщо старший біт дорівнює "1", число інтерпретується як від'ємне, а інші 15 бітів інтерпретуються з використанням (http://en.wikipedia.org/wiki/2%27s_complement[додаткового коду]).
[%hardbreaks]


[float]
=== Синтаксис
`unsigned int var = val;`


[float]
=== Параметри
`var`: ім'я змінної. +
`val`: значення, яке ви їй призначаєте.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Приклад коду
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
unsigned int ledPin = 13;
----
[%hardbreaks]

[float]
=== Нотатки
Коли беззнакові змінні мають перевищувати свою максимальну місткість, вони "переповнюються" назад до 0, і навпаки:

[source,arduino]
----
unsigned int x;
x = 0;
x = x - 1;  // x зараз 65535
x = x + 1;  // x зараз 0 - переповнення!
----

Математичні обчислення зі змінними без знаку можуть дати несподіваний результат, навіть якщо ваша змінна без знаку ніколи не переповнюється.

Мікроконтролер (MCU) застосовує такі правила:

Обчислення виконуються в області видимості цільової змінної. Наприклад, якщо змінна має знак, він буде виконувати математичні операції зі знаком, навіть якщо обидві вхідні змінні є беззнаковими.

Однак при обчисленні, яке вимагає проміжного результату, область видимості проміжного результату не вказується кодом. У цьому випадку MCU буде виконувати обчислення без знаку для проміжного результату, оскільки обидві вхідні змінні без знаку!


[source,arduino]
----
unsigned int x = 5;
unsigned int y = 10;
int result;

result = x - y; // 5 - 10 = -5, очікувано
result = (x - y) / 2; // 5 - 10 = 65530!  65530/2 = 32765

// рішення: використовуйте змінні зі знаком, або виконуйте обчислення покроково.
result = x - y; // 5 - 10 = -5, очікувано
result = result / 2;  //  -5/2 = -2 (лише цілочисельне обчислення, десяткові розряди відкидаються)
----
Навіщо взагалі використовувати змінні без знаку?

- Поведінка з переповненням є бажаною іноді, наприклад, для лічильників.
- Змінна зі знаком занадто мала, але ви хочете уникнути втрати пам'яті та швидкості, пов'язаної з long/float.
--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Додатково

[role="language"]
* #LANGUAGE# link:../../constants/integerconstants[Цілочисельні константи]

--
// SEE ALSO SECTION ENDS
