---
title: analogWriteResolution()
categories: [ "Functions" ]
subCategories: [ "Analog I/O" ]
---




= analogWriteResolution()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
`analogWriteResolution()` є розширенням Analog API для Arduino Due.

`analogWriteResolution()` встановлює роздільну здатність функції `analogWrite()`. За замовчуванням це 8 біт (значення від 0 до 255) для зворотної сумісності з платами на базі AVR.

*Due* має такі апаратні можливості:

* 12 виводів, які за замовчуванням мають 8-бітний ШІМ, як у плат на базі AVR. Їх можна змінити на 12-бітну роздільну здатність.
* 2 виводи з 12-бітним ЦАП (цифро-аналоговим перетворювачем)

Встановивши роздільну здатність запису на 12, ви можете використовувати `analogWrite()` зі значеннями від 0 до 4095, щоб використовувати повну роздільну здатність ЦАП або встановлювати ШІМ-сигнал без переповнення.

*Zero* має такі апаратні можливості:

* 10 виводів, які за замовчуванням мають 8-бітний ШІМ, як у плат на базі AVR. Їх можна змінити на 12-бітну роздільну здатність.
* 1 вивід з 10-бітним ЦАП (цифро-аналоговим перетворювачем).

Встановивши роздільну здатність запису на 10, ви можете використовувати `analogWrite()` зі значеннями від 0 до 1023, щоб використовувати повну роздільну здатність ЦАП

Сімейство плат *MKR* має такі апаратні можливості:

* 4 виводи, які за замовчуванням мають 8-бітний ШІМ, як у плат на базі AVR. Їх можна змінити з 8 (за замовчуванням) на 12-бітну роздільну здатність.
* 1 вивід з 10-бітним ЦАП (цифро-аналоговим перетворювачем)

Встановивши роздільну здатність запису на 12 біт, ви можете використовувати `analogWrite()` зі значеннями від 0 до 4095 для ШІМ-сигналів; встановіть 10 біт на виводі ЦАП, щоб використовувати повну роздільну здатність ЦАП 1024 значення.
[%hardbreaks]


[float]
=== Syntax
`analogWriteResolution(bits)`


[float]
=== Parameters
`bits`: визначає роздільну здатність (у бітах) значень, що використовуються у функції `analogWrite()`. Значення може бути від 1 до 32. Якщо ви виберете роздільну здатність більшу або меншу за апаратні можливості вашої плати, значення, що використовується в `analogWrite()`, буде або обрізане, якщо воно занадто велике, або заповнене нулями, якщо воно занадто мале. Деталі див. у примітці нижче.


[float]
=== Returns
Нічого

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Поясніть код

[source,arduino]
----
void setup() {
  // open a serial connection
  Serial.begin(9600);
  // make our digital pin an output
  pinMode(11, OUTPUT);
  pinMode(12, OUTPUT);
  pinMode(13, OUTPUT);
}

void loop() {
  // read the input on A0 and map it to a PWM pin
  // with an attached LED
  int sensorVal = analogRead(A0);
  Serial.print("Analog Read) : ");
  Serial.print(sensorVal);

  // the default PWM resolution
  analogWriteResolution(8);
  analogWrite(11, map(sensorVal, 0, 1023, 0, 255));
  Serial.print(" , 8-bit PWM value : ");
  Serial.print(map(sensorVal, 0, 1023, 0, 255));

  // change the PWM resolution to 12 bits
  // the full 12 bit resolution is only supported
  // on the Due
  analogWriteResolution(12);
  analogWrite(12, map(sensorVal, 0, 1023, 0, 4095));
  Serial.print(" , 12-bit PWM value : ");
  Serial.print(map(sensorVal, 0, 1023, 0, 4095));

  // change the PWM resolution to 4 bits
  analogWriteResolution(4);
  analogWrite(13, map(sensorVal, 0, 1023, 0, 15));
  Serial.print(", 4-bit PWM value : ");
  Serial.println(map(sensorVal, 0, 1023, 0, 15));

  delay(5);
}
----
[%hardbreaks]

[float]
=== Notes and Warnings
Якщо ви встановите значення `analogWriteResolution()` вище за можливості вашої плати, Arduino відкине зайві біти. Наприклад: при використанні Due з `analogWriteResolution(16)` на виводі 12-бітного ЦАП, використовуватимуться лише перші 12 біт значень, переданих у `analogWrite()`, а останні 4 біти будуть відкинуті.

Якщо ви встановите значення `analogWriteResolution()` нижче за можливості вашої плати, відсутні біти будуть *заповнені нулями* для досягнення розміру, необхідного апаратним забезпеченням. Наприклад: при використанні Due з analogWriteResolution(8) на виводі 12-бітного ЦАП, Arduino додасть 4 нульових біти до 8-бітного значення, що використовується у `analogWrite()`, щоб отримати необхідні 12 біт.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE# link:../../analog-io/analogwrite[analogWrite()]
* #LANGUAGE# link:../../analog-io/analogread[analogRead()]
* #LANGUAGE# link:../../math/map[map()]

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/AnalogInputPins[Description of the analog input pins^]

--
// SEE ALSO SECTION ENDS
