---
title: analogWrite()
categories: [ "Functions" ]
subCategories: [ "Analog I/O" ]
---





= analogWrite()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Записує аналогове значення (http://arduino.cc/en/Tutorial/PWM[ШІМ-сигнал]) на вивід. Може використовуватися для світіння світлодіода з різною яскравістю або керування двигуном з різними швидкостями. Після виклику `analogWrite()` вивід буде генерувати стабільну прямокутну хвилю із заданою шпаруватістю аж до наступного виклику `analogWrite()` (або виклику `digitalRead()` чи `digitalWrite()`) для того самого виводу.

[options="header"]

|=========================================================================================================================
| Board                                      | PWM Pins +*+                   | PWM Frequency
| UNO (R3 and earlier), Nano, Mini           | 3, 5, 6, 9, 10, 11             | 490 Hz (pins 5 and 6: 980 Hz)
| UNO R4 (Minima, WiFi) +*+                  | 3, 5, 6, 9, 10, 11             | 490 Hz
| Mega                                       | 2 - 13, 44 - 46                | 490 Hz (pins 4 and 13: 980 Hz)
| GIGA R1 +**+                               | 2 - 13                         | 500 Hz
| Leonardo, Micro, Yún                       | 3, 5, 6, 9, 10, 11, 13         | 490 Hz (pins 3 and 11: 980 Hz)
| UNO WiFi Rev2, Nano Every                  | 3, 5, 6, 9, 10                 | 976 Hz
| MKR boards +*+                             | 0 - 8, 10, A3, A4              | 732 Hz
| MKR1000 WiFi +**+                          | 0 - 8, 10, 11, A3, A4          | 732 Hz
| Zero +**+                                  | 3 - 13, A0, A1                 | 732 Hz
| Nano 33 IoT +**+                           | 2, 3, 5, 6, 9 - 12, A2, A3, A5 | 732 Hz
| Nano 33 BLE/BLE Sense +****+               | 1 - 13, A0 - A7                | 500 Hz
| Due +***+                                  | 2-13                           | 1000 Hz
| 101                                        | 3, 5, 6, 9                     | pins 3 and 9: 490 Hz, pins 5 and 6: 980 Hz
|=========================================================================================================================

+*+ Ці виводи офіційно підтримують ШІМ (PWM). Хоча деякі плати мають додаткові виводи, здатні до ШІМ, їх використання рекомендується лише для досвідчених користувачів, які можуть врахувати наявність таймерів та можливі конфлікти з іншим використанням цих виводів. +
+**+ Окрім можливостей ШІМ на зазначених вище виводах, плати MKR, Nano 33 IoT, Zero та UNO R4 мають справжній аналоговий вихід при використанні `analogWrite()` на виводі `DAC0` (`A0`). +
+***+ Окрім можливостей ШІМ на зазначених вище виводах, плати Due та GIGA R1 мають справжній аналоговий вихід при використанні `analogWrite()` на виводах `DAC0` та `DAC1`. +
+****+ Одночасно можна використовувати лише 4 різні виводи. Увімкнення ШІМ на більше ніж 4 виводах перерве виконання скетчу та вимагатиме скидання плати для завантаження нового скетчу знову. +

[%hardbreaks]

Вам не потрібно викликати `pinMode()` для встановлення виводу як виходу перед викликом `analogWrite()`.
Функція `analogWrite` не має нічого спільного з аналоговими виводами або функцією `analogRead`.
[%hardbreaks]


[float]
=== Syntax
`analogWrite(pin, value)`


[float]
=== Parameters
`pin`: вивід Arduino для запису. Дозволені типи даних: `int`. +
`value`: робочий цикл (шпаруватість): від 0 (завжди вимкнено) до 255 (завжди увімкнено). Дозволені типи даних: `int`.


[float]
=== Returns
Нічого

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
Встановлює струм на світлодіод пропорційно значенню, зчитаному з потенціометра.


[source,arduino]
----
int ledPin = 9;      // LED connected to digital pin 9
int analogPin = 3;   // potentiometer connected to analog pin 3
int val = 0;         // variable to store the read value

void setup() {
  pinMode(ledPin, OUTPUT);  // sets the pin as output
}

void loop() {
  val = analogRead(analogPin);  // read the input pin
  analogWrite(ledPin, val / 4); // analogRead values go from 0 to 1023, analogWrite values from 0 to 255
}
----
[%hardbreaks]


[float]
=== Notes and Warnings
ШІМ-сигнали, згенеровані на виводах 5 та 6, матимуть вищу за очікувану шпаруватість. Це пов'язано із взаємодією з функціями `millis()` та `delay()`, які спільно використовують той самий внутрішній таймер, що й для генерації цих ШІМ-сигналів. Здебільшого це буде помітно при низьких налаштуваннях шпаруватості (наприклад, 0 - 10) і може призвести до того, що значення 0 не повністю вимикатиме вихід на виводах 5 і 6.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE# link:../../zero-due-mkr-family/analogwriteresolution[analogWriteResolution()]

[role="definition"]
* #DEFINITION# http://arduino.cc/en/Tutorial/PWM[PWM^]

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Blink[Blink^]

--
// SEE ALSO SECTION ENDS
