---
title: min()
categories: [ "Functions" ]
subCategories: [ "Math" ]
---





= min(x, y)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Обчислює мінімальне з двох чисел.
[%hardbreaks]


[float]
=== Syntax
`min(x, y)`


[float]
=== Parameters
`x`: перше число. Дозволені типи даних: будь-який тип даних. +
`y`: друге число. Дозволені типи даних: будь-який тип даних.


[float]
=== Returns
Менше з двох чисел.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Код гарантує, що значення ніколи не стає більшим за 100.

[source,arduino]
----
sensVal = min(sensVal, 100);  // assigns sensVal to the smaller of sensVal or 100
                              // ensuring that it never gets above 100.
----
[%hardbreaks]

[float]
=== Notes and Warnings
Можливо, це не зовсім інтуїтивно, але `max()` часто використовується для обмеження нижньої межі діапазону змінної, тоді як `min()` використовується для обмеження верхньої межі діапазону.

Через те, як реалізовано функцію `min()`, уникайте використання інших функцій всередині дужок, це може призвести до неправильних результатів
[source,arduino]
----
min(a++, 100);  // avoid this - yields incorrect results

min(a, 100);
a++;  // use this instead - keep other math outside the function
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE# link:../abs[abs()]
* #LANGUAGE# link:../constrain[constrain()]
* #LANGUAGE# link:../map[map()]
* #LANGUAGE# link:../max[max()]
* #LANGUAGE# link:../pow[pow()]
* #LANGUAGE# link:../sq[sq()]
* #LANGUAGE# link:../sqrt[sqrt()]

--
// SEE ALSO SECTION ENDS
