---
title: scope
categories: [ "Variables" ]
subCategories: [ "Variable Scope & Qualifiers" ]
---





= variable scope


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Змінні в мові програмування C++, яку використовує Arduino, мають властивість - scope (область видимості). Це на відміну від ранніх версій мов, таких як BASIC, де кожна змінна є _глобальною_ змінною.

Глобальна змінна — це така змінна, яку можуть бачити всі функції в програмі. Локальні змінні видимі лише для тієї функції, в якій вони оголошені. В середовищі Arduino будь-яка змінна, оголошена поза межами функції (наприклад, `link:../../../structure/sketch/setup[setup()]`, `link:../../../structure/sketch/loop[loop()]`, тощо), є _глобальною_ змінною.

Коли програми стають більшими і складнішими, локальні змінні є корисним способом гарантувати, що лише одна функція має доступ до своїх власних змінних. Це запобігає помилкам програмування, коли одна функція ненавмисно змінює змінні, які використовуються іншою функцією.

Іноді буває зручно оголошувати ініціалізовану змінну всередині циклу `link:../../../structure/control-structure/for[for]`. Це створює змінну, до якої можна отримати доступ лише зсередини дужок циклу link:../../../structure/control-structure/for[`for`].
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Приклад коду
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
int gPWMval;  // доступ до змінної з будь якого методу чи функції в межах файлу

void setup() {
  // ...
}

void loop() {
  int i;    // доступ до "i" та її виклик існує лише в межах циклу
  float f;  // доступ до "f" та її виклик існує лише в межах циклу
  // ...

  for (int j = 0; j < 100; j++) {
    // todo
  }
}
----
[%hardbreaks]


--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Додатково

--
// SEE ALSO SECTION ENDS
