---
title: volatile
categories: [ "Variables" ]
subCategories: [ "Variable Scope & Qualifiers" ]
---





= volatile


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
`volatile` — ключове слово, відоме як _модифікатор_ змінної, що зазвичай використовується перед типом змінної, щоб змінити поведінку компілятора під час опрацювання змінної.

Оголошення змінної `volatile` є директивою для компілятора. Компілятор – це програмне забезпечення, яке перетворює ваш код на C/C++ у машинний код, а саме інструкції для виконуючого процесора Atmega, який є основним елементом мікроконтролерів Arduino.

Команда компілятору завантажувати змінну з оперативної пам’яті (RAM), а не з регістру зберігання (який є тимчасовим місцем у пам'яті, де змінні зберігаються). За певних несприятливих умов значення змінної, що зберігається в регістрах, може бути неточним.

Змінну слід оголошувати як `volatile` щоразу, коли її значення може бути змінено поза її видимістю в блокові коду, в якій вона ініціалізується. Наприклад, в потоках, що виконуються одночасно. В Arduino єдине місце, де це ймовірно може статися, – це блоки коду, пов’язані з перериваннями `interrupt service routine`.

[float]
=== вибір типу int або long
Якщо змінна `volatile` більша за байт (наприклад, 16-бітний int або 32-бітний long), мікроконтролер не може прочитати її за один прохід, оскільки це 8-бітний мікропроцессор. Це означає, що поки ваш блок коду (наприклад, цикл `loop`) читає перші 8 біт змінної, переривання вже може змінити інші 8 біт. Це призведе до зчитування випадкових значень змінної.

Рішення:

Під час зчитування змінної переривання мають бути вимкнені, щоб вони не могли зіпсувати біти, поки вони читаються.
Існує декілька способів це зробити:

1. link:../../../functions/interrupts/nointerrupts[noInterrupts]

2. використовуйте `ATOMIC_BLOCK`. Атомарна операція — це поодинока операція MCU — найменша можлива одиниця активності мікропроцессора.


[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Приклад коду
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄

Модифікатор `volatile` гарантує та забезпечує ситуацію в результаті якої зміни змінної `changed` будуть негайно видимі у `loop()`. Без модифікатора `volatile`, змінна `changed` може бути завантажена в регістр під час входу у функцію і більше не буде оновлюватися до закінчення дії функції.

[source,arduino]
----
// мигання світлодіодом протягом 1 с, якщо вхідне значення
// змінилося протягом попередньої секунди.

volatile byte changed = 0;

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  attachInterrupt(digitalPinToInterrupt(2), toggle, CHANGE);
}

void loop() {
  if (changed == 1) {
    // toggle було викликано з переривань!

    changed = 0;

    // мигання світлодіодом протягом 200 мс
    digitalWrite(LED_BUILTIN, HIGH);
    delay(200);
    digitalWrite(LED_BUILTIN, LOW);
  }
}

void toggle() {
  changed = 1;
}
----

Щоб отримати доступ до змінної, розмір якої перевищує 8-біт даних мікроконтролера, використовуйте `ATOMIC_BLOCK`. Ця дериктива гарантує, що змінна зчитується в межах атомарної операції, тобто її вміст не може бути змінено під час читання.

[source,arduino]
----
#include <util/atomic.h> // бібліотека що включає 'атомарну' директиву ATOMIC_BLOCK.
volatile int input_from_interrupt;

// Десь в блокові коду. Наприклад, в середині циклу
  ATOMIC_BLOCK(ATOMIC_RESTORESTATE) {
    // код з заблокованими перериваннями 
    // виконання послідовних атомарних операцій не переривається
    int result = input_from_interrupt;
  }
----



--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== Додатково

[role="language"]
* link:../../../functions/external-interrupts/attachinterrupt[attachInterrupt]

--
// SEE ALSO SECTION ENDS
