---
title: volatile
categories: [ "Variables" ]
subCategories: [ "Variable Scope & Qualifiers" ]
---





= volatile keyword


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
`volatile` — це ключове слово, відоме як _кваліфікатор_ змінної, воно зазвичай використовується перед типом даних змінної, щоб змінити те, як компілятор і подальша програма обробляють змінну.

Оголошення змінної `volatile` є директивою для компілятора. Компілятор – це програмне забезпечення, яке перетворює ваш код на C/C++ у машинний код, що є реальними інструкціями для чіпа Atmega всередині Arduino.

Зокрема, це вказує компілятору завантажувати змінну з оперативної пам’яті (RAM), а не з регістра зберігання (який є тимчасовим місцеположенням у пам'яті, де змінні програми зберігаються і маніпулюються). За певних умов значення змінної, що зберігається в регістрах, може бути неточним.

Змінну слід оголошувати як `volatile` щоразу, коли її значення може бути змінено чимось поза контролем секції коду, в якій вона з'являється, наприклад, потоком, що виконується одночасно. В Arduino єдине місце, де це ймовірно може статися, – це секції коду, пов’язані з перериваннями, які називаються підпрограмою обслуговування переривань (interrupt service routine).

[float]
=== int або long volatiles
Якщо змінна `volatile` більша за байт (наприклад, 16-бітний int або 32-бітний long), мікроконтролер не може прочитати її за один крок, оскільки це 8-бітний мікроконтролер. Це означає, що поки ваш основний розділ коду (наприклад, ваш цикл `loop`) читає перші 8 біт змінної, переривання вже може змінити другі 8 біт. Це призведе до випадкових значень для змінної.

Вирішення:

Під час читання змінної переривання повинні бути вимкнені, щоб вони не могли зіпсувати біти, поки вони читаються.
Існує кілька способів це зробити:

1. #LANGUAGE# link:../../../functions/interrupts/nointerrupts[noInterrupts]

2. використовуйте макрос ATOMIC_BLOCK. Атомарні операції — це поодинокі операції MCU — найменша можлива одиниця.


[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄

Модифікатор `volatile` гарантує, що зміни змінної `changed` будуть негайно видимі у `loop()`. Без модифікатора `volatile`, змінна `changed` може бути завантажена в регістр при вході у функцію і більше не буде оновлюватися до закінчення функції.

[source,arduino]
----
// Flashes the LED for 1 s if the input has changed
// in the previous second.

volatile byte changed = 0;

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  attachInterrupt(digitalPinToInterrupt(2), toggle, CHANGE);
}

void loop() {
  if (changed == 1) {
    // toggle() has been called from interrupts!

    // Reset changed to 0
    changed = 0;

    // Blink LED for 200 ms
    digitalWrite(LED_BUILTIN, HIGH);
    delay(200);
    digitalWrite(LED_BUILTIN, LOW);
  }
}

void toggle() {
  changed = 1;
}
----

Щоб отримати доступ до змінної, розмір якої перевищує 8-бітну шину даних мікроконтролера, використовуйте макрос `ATOMIC_BLOCK`. Макрос гарантує, що змінна зчитується в межах атомарної операції, тобто її вміст не може бути змінено під час читання.

[source,arduino]
----
#include <util/atomic.h> // this library includes the ATOMIC_BLOCK macro.
volatile int input_from_interrupt;

// Somewhere in the code, e.g. inside loop()
  ATOMIC_BLOCK(ATOMIC_RESTORESTATE) {
    // code with interrupts blocked (consecutive atomic operations will not get interrupted)
    int result = input_from_interrupt;
  }
----



--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE# link:../../../functions/external-interrupts/attachinterrupt[attachInterrupt]

--
// SEE ALSO SECTION ENDS
