---
title: "isSpace()"
categories: [ "Functions" ]
subCategories: [ "Characters" ]
---





= isSpace(thisChar)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Перевіряє, чи є символ пробільним символом. Повертає true, якщо аргумент є пробілом (space), подачею форми (`'\f'`), символом нового рядка (`'\n'`), поверненням каретки (`'\r'`), горизонтальною табуляцією (`'\t'`) або вертикальною табуляцією (`'\v'`).
[%hardbreaks]


[float]
=== Синтаксис
`isSpace(thisChar)`


[float]
=== Параметри
`thisChar`: змінна. Дозволені типи даних: `char`.


[float]
=== Повертає
`true`: якщо thisChar є пробільним символом.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Приклад коду

[source,arduino]
----
if (isSpace(myChar)) {  // tests if myChar is a white-space character
  Serial.println("The character is white-space");
}
else {
  Serial.println("The character is not white-space");
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== Див. також

[role="language"]
* #LANGUAGE#  link:../../../variables/data-types/char[char]
* #LANGUAGE#  link:../../../structure/control-structure/if[if (conditional operators)]
* #LANGUAGE#  link:../../../structure/control-structure/while[while (conditional operators)]
* #LANGUAGE# link:../../communication/serial/read[read()]

--
// SEE ALSO SECTION ENDS
