---
title: "&="
title_expanded: compound bitwise and
categories: [ "Structure" ]
subCategories: [ "Compound Operators" ]
---





= &= Compound Bitwise AND (Складене побітове І)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Складений оператор побітового І `&=` часто використовується зі змінною та константою для примусового встановлення певних бітів змінної у стан LOW (в 0). У посібниках з програмування це часто називають "очищенням" або "скиданням" бітів.
[%hardbreaks]

Огляд оператора Побітове І `&`:

   0  0  1  1    операнд1
   0  1  0  1    операнд2
   ----------
   0  0  0  1    (операнд1 & операнд2) - повернутий результат
[%hardbreaks]

[float]
=== Syntax
`x &= y; // еквівалентно x = x & y;`


[float]
=== Parameters
`x`: змінна. Дозволені типи даних: `char`, `int`, `long`. +
`y`: змінна або константа. Дозволені типи даних: `char`, `int`, `long`.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
Біти, до яких застосовано "побітове І" з 0, очищаються (встановлюються в 0). Тому, якщо myByte — це змінна типу byte,

[source,arduino]
----
myByte & 0b00000000 = 0;
----

Біти, до яких застосовано "побітове І" з 1, залишаються без змін:

[source,arduino]
----
myByte & 0b11111111 = myByte;
----
[%hardbreaks]

[float]
=== Notes and Warnings
Оскільки у випадку з побітовим оператором ми працюємо безпосередньо з бітами, зручно використовувати двійкове форматування для констант. Числа мають те саме значення і в інших представленнях, просто їх не так легко зрозуміти. Також `0b00000000` показано для ясності, але нуль у будь-якому числовому форматі є нулем.

Отже, щоб очистити (встановити в нуль) 0-й та 1-й біти змінної, залишивши решту без змін, використовуйте складений оператор побітового І (&=) з константою 0b11111100:

   1  0  1  0  1  0  1  0    змінна
   1  1  1  1  1  1  0  0    маска
   ----------------------
   1  0  1  0  1  0  0  0

    біти без змін
                     очищені біти

Ось те ж саме представлення, де біти змінної замінено символом x:

   x  x  x  x  x  x  x  x    змінна
   1  1  1  1  1  1  0  0    маска
   ----------------------
   x  x  x  x  x  x  0  0

    біти без змін
                     очищені біти

Тож якщо:

[source,arduino]
----
myByte = 0b10101010;
myByte &= 0b11111100;  // результат 0b10101000
----

[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE#  link:../../bitwise-operators/bitwiseand[& Bitwise AND]

--
// SEE ALSO SECTION ENDS
