---
title: "|="
title_expanded: compound bitwise or
categories: [ "Structure" ]
subCategories: [ "Compound Operators" ]
---

= |= Compound Bitwise OR (Складене побітове АБО)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Складений оператор побітового АБО `|=` часто використовується зі змінною та константою для "встановлення" (в значення 1) певних бітів у змінній.
[%hardbreaks]

Огляд оператора Побітове АБО `|`:

   0  0  1  1    операнд1
   0  1  0  1    операнд2
   ----------
   0  1  1  1    (операнд1 | операнд2) - повернутий результат
[%hardbreaks]

[float]
=== Syntax
`x |= y; // еквівалентно x = x | y;`


[float]
=== Parameters
`x`: змінна. Дозволені типи даних: `char`, `int`, `long`. +
`y`: змінна або константа. Дозволені типи даних: `char`, `int`, `long`.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
Біти, до яких застосовано "побітове АБО" з 0, залишаються без змін. Тому, якщо myByte — це змінна типу byte,
[source,arduino]
----
myByte | 0b00000000 = myByte;
----

Біти, до яких застосовано "побітове АБО" з 1, встановлюються в 1:
[source,arduino]
----
myByte | 0b11111111 = 0b11111111;
----
[%hardbreaks]

[float]
=== Notes and Warnings
Оскільки у випадку з побітовим оператором ми працюємо безпосередньо з бітами, зручно використовувати двійкове форматування для констант. Числа мають те саме значення і в інших представленнях, просто їх не так легко зрозуміти. Також `0b00000000` показано для ясності, але нуль у будь-якому числовому форматі є нулем.
[%hardbreaks]

Отже, щоб встановити 0-й та 1-й біти змінної, залишивши решту без змін, використовуйте складений оператор побітового АБО (|=) з константою 0b00000011:

   1  0  1  0  1  0  1  0    змінна
   0  0  0  0  0  0  1  1    маска
   ----------------------
   1  0  1  0  1  0  1  1

    біти без змін
                     встановлені біти


Ось те ж саме представлення, де біти змінної замінено символом x:

   x  x  x  x  x  x  x  x    змінна
   0  0  0  0  0  0  1  1    маска
   ----------------------
   x  x  x  x  x  x  1  1

    біти без змін
                     встановлені біти

Тож якщо:
[source,arduino]
----
myByte = 0b10101010;
myByte |= 0b00000011 == 0b10101011;
----

--
// HOW TO USE SECTION ENDS




//SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE#  link:../../bitwise-operators/bitwiseor[| Bitwise OR]

--
// SEE ALSO SECTION ENDS
