---
title: attachInterrupt()
categories: [ "Functions" ]
subCategories: [ "External Interrupts" ]
---

= attachInterrupt()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
*Цифрові контакти з перериваннями*

Першим параметром для `attachInterrupt()` є номер переривання. Зазвичай потрібно використовувати `digitalPinToInterrupt(pin)`, щоб перетворити фактичний цифровий контакт у конкретний номер переривання. Наприклад, якщо ви підключаєтеся до контакту 3, використовуйте `digitalPinToInterrupt(3)` як перший параметр для `attachInterrupt()`.

[options="header"]
|===================================================
|Плата                                            |Цифрові контакти, доступні для переривань| Примітки
|Uno Rev3, Nano, Mini, інші на базі 328            |2, 3|
|UNO R4 Minima, UNO R4 WiFi                       |2, 3|
|Uno WiFi Rev2, Nano Every                        |Всі цифрові контакти|
|Mega, Mega2560, MegaADK                          |2, 3, 18, 19, 20, 21 |(*контакти 20 та 21* недоступні для використання в якості переривань, коли вони використовуються для зв'язку I2C; вони також мають зовнішні підтягуючі резистори, які не можна вимкнути)
|Micro, Leonardo                                  |0, 1, 2, 3, 7|
|Zero                                             |0-3, 5-13, A0-A5| Контакт 4 не може бути використаний як переривання.
|Сімейство плат MKR                               |0, 1, 4, 5, 6, 7, 8, 9, A1, A2|
|Nano 33 IoT                                      |2, 3, 9, 10, 11, 13, A1, A5, A7|
|Nano 33 BLE, Nano 33 BLE Sense (rev 1 та 2)       |всі контакти|
|Nano RP2040 Connect                              |0-13, A0-A5|
|Nano ESP32                                       |всі контакти|
|GIGA R1 WiFi                                     |всі контакти|
|Due                                              |всі цифрові контакти|
|101                                              |всі цифрові контакти | (Тільки контакти 2, 5, 7, 8, 10, 11, 12, 13 працюють з *CHANGE*)
|===================================================

[%hardbreaks]

[float]
=== Notes and Warnings

*Примітка* +
Усередині прикріпленої функції `delay()` не працюватиме, а значення, яке повертає `millis()`, не збільшуватиметься. Послідовні дані, отримані під час виконання функції, можуть бути втрачені. Будь-які змінні, які ви змінюєте всередині прикріпленої функції, слід оголошувати як `volatile`. Дивіться розділ про ISR нижче для отримання додаткової інформації.
[%hardbreaks]

[float]
== Використання переривань
Переривання корисні для того, щоб речі відбувалися автоматично в програмах мікроконтролера і можуть допомогти вирішити проблеми з таймінгами. Зручними завданнями для використання переривання можуть бути зчитування роторного енкодера або моніторинг вводу користувача.

Якби ви хотіли переконатися, що програма завжди ловить імпульси від роторного енкодера, щоб вона ніколи не пропускала імпульс, було б дуже складно написати програму, яка робила б щось інше, оскільки програмі довелося б постійно опитувати лінії датчика для енкодера, щоб ловити імпульси, коли вони виникають. Інші датчики також мають подібну динаміку інтерфейсу, наприклад спроба прочитати датчик звуку, який намагається зловити клік, або інфрачервоний датчик з щілиною (фотопереривник), що намагається зловити падіння монети. У всіх цих ситуаціях використання переривання може звільнити мікроконтролер для виконання іншої роботи, не пропускаючи вхідний сигнал.

[float]
== Про підпрограми обслуговування переривань (ISR)
ISR - це особливі функції, які мають унікальні обмеження, яких не має більшість інших функцій. ISR не може мати параметрів, і вони не повинні нічого повертати.

Загалом, ISR повинна бути якомога коротшою і швидшою. Якщо ваш скетч використовує декілька ISR, за раз може виконуватись тільки одна, інші переривання будуть виконані після завершення поточної у порядку, що залежить від їх пріоритету. `millis()` покладається на переривання для підрахунку, тому він ніколи не буде збільшуватись всередині ISR. Оскільки `delay()` вимагає переривань для роботи, вона не буде працювати, якщо викликана всередині ISR. `micros()` працює спочатку, але почне поводитися непередбачувано через 1-2 мс. `delayMicroseconds()` не використовує жодного лічильника, тому працюватиме як зазвичай.

Зазвичай для передачі даних між ISR та основною програмою використовуються глобальні змінні. Щоб переконатися, що змінні, які використовуються спільно між a ISR і основною програмою, оновлюються правильно, оголосіть їх як `volatile`.

Для отримання додаткової інформації про переривання див. http://gammon.com.au/interrupts[нотатки Ніка Геммона].

[float]
=== Syntax
`attachInterrupt(digitalPinToInterrupt(pin), ISR, mode)` (рекомендовано) +
`attachInterrupt(interrupt, ISR, mode)` (не рекомендовано) +
`attachInterrupt(pin, ISR, mode)` (Не рекомендовано. Крім того, цей синтаксис працює лише на платах Arduino SAMD, Uno WiFi Rev2, Due та 101.)


[float]
=== Parameters
`interrupt`: номер переривання. Допустимі типи даних: `int`. +
`pin`: номер контакту Arduino. +
`ISR`: ISR для виклику при виникненні переривання; ця функція не повинна приймати жодних параметрів і нічого не повертати. Ця функція іноді називається підпрограмою обслуговування переривання. +
`mode`: визначає, коли переривання повинно бути ініційовано. Попередньо визначені чотири константи як дійсні значення: +

* *LOW*, щоб викликати переривання, коли на контакті низький рівень сигналу, +
* *CHANGE*, щоб викликати переривання, коли значення на контакті змінюється +
* *RISING*, щоб викликати переривання, коли контакт переходить з низького на високий стан, +
* *FALLING* для випадків, коли контакт переходить з високого стану на низький. +

Плати Due, Zero та MKR1000 також дозволяють: +

* *HIGH*, щоб викликати переривання, коли на контакті високий рівень сигналу.


[float]
=== Returns
Нічого

--
// OVERVIEW SECTION ENDS

// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code


[source,arduino]
----
const byte ledPin = 13;
const byte interruptPin = 2;
volatile byte state = LOW;

void setup() {
  pinMode(ledPin, OUTPUT);
  pinMode(interruptPin, INPUT_PULLUP);
  attachInterrupt(digitalPinToInterrupt(interruptPin), blink, CHANGE);
}

void loop() {
  digitalWrite(ledPin, state);
}

void blink() {
  state = !state;
}
----

[float]
=== Номери переривань
Зазвичай ви повинні використовувати `digitalPinToInterrupt(pin)`, замість того, щоб вказувати номер переривання безпосередньо у своєму скетчі. Специфічні контакти з перериваннями та їх відповідність номеру переривання відрізняється для кожного типу плати. Пряме використання номерів переривань може здаватися простим, але це може спричинити проблеми сумісності, коли ваш скетч виконується на іншій платі.

Однак старі скетчі часто мають безпосередні номери переривань. Часто використовувався номер 0 (для цифрового контакту 2) або номер 1 (для цифрового контакту 3). Наведена нижче таблиця показує доступні контакти переривань на різних платах.

Зауважте, що в таблиці нижче номери переривань стосуються номера, який буде передано до `attachInterrupt()`. З історичних причин нумерація не завжди відповідає напряму нумерації переривань на мікросхемі ATmega (наприклад, int.0 відповідає INT4 на мікросхемі ATmega2560).

[options="header"]
|===================================================
|Плата                            | int.0 | int.1 | int.2 | int.3 | int.4 | int.5
|Uno, Ethernet                    | 2 | 3 | | | |
|Mega2560                         | 2 | 3 | 21 | 20 | 19 | 18
|На базі 32u4 (напр. Leonardo, Micro) | 3 | 2 | 0 | 1 | 7 |
|===================================================

Для плат Uno WiFi Rev2, Due, Zero, MKR Family та 101 *номер переривання = номеру контакту*.

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

--
// SEE ALSO SECTION ENDS
