---
title: ">"
title_expanded: greater than
categories: [ "Structure" ]
subCategories: [ "Comparison Operators" ]
---





= > Greater than (Більше)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Порівнює змінну ліворуч зі значенням або змінною праворуч від оператора. Повертає true, якщо операнд ліворуч більший за операнд праворуч. Зверніть увагу, що ви можете порівнювати змінні різних типів даних, але це може призвести до непередбачуваних результатів. Тому рекомендується порівнювати змінні одного типу даних, включно з їх знаковістю (знакові/беззнакові).
[%hardbreaks]


[float]
=== Syntax
`x > y;  // істинно (true), якщо x більше за y, і хибно (false), якщо x дорівнює або менше y`


[float]
=== Parameters
`x`: змінна. Дозволені типи даних: `int`, `float`, `double`, `byte`, `short`, `long`. +
`y`: змінна або константа. Дозволені типи даних: `int`, `float`, `double`, `byte`, `short`, `long`.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code

[source,arduino]
----
if (x > y) {  // перевіряє, чи x більше за y
  // виконує дії тільки якщо результат порівняння є true
}
----
[%hardbreaks]

[float]
=== Notes and Warnings
Додатні числа більші за від'ємні.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== See also

[role="language"]

--
// SEE ALSO SECTION ENDS
