---
title: "//"
title_expanded: single line comment
categories: [ "Structure" ]
subCategories: [ "Further Syntax" ]
---





= // Однорядковий коментар


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
*Коментарі* — це рядки в програмі, які використовуються для того, щоб інформувати вас або інших користувачів про те, як працює програма. Вони ігноруються компілятором і не експортуються до процесора, тому не займають місця у флеш-пам'яті мікроконтролера. Єдина мета коментарів — допомогти вам зрозуміти (або запам'ятати), чи повідомити іншим, як працює ваша програма.
[%hardbreaks]

*Однорядковий коментар* починається з `//` (двох скісних рисок поруч). Цей коментар автоматично закінчується в кінці рядка. Все, що йде після `//` до кінця рядка, буде проігноровано компілятором.
--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Приклад коду
Існує два різні способи позначити рядок як коментар:

[source,arduino]
----
// pin 13 has an LED connected on most Arduino boards.
// give it a name:
int led = 13;
digitalWrite(led, HIGH);  // turn the LED on (HIGH is the voltage level)
----
[%hardbreaks]

[float]
=== Примітки та попередження
Під час експериментів з кодом, "закоментовування" частин вашої програми є зручним способом видалити рядки, які можуть містити помилки. Це залишає рядки в коді, але перетворює їх на коментарі, тому компілятор їх просто ігнорує. Це може бути особливо корисним, коли ви намагаєтеся знайти проблему, або коли програма відмовляється компілюватися, а помилка компілятора є загадковою або не допомагає.
[%hardbreaks]


--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Дивіться також

[role="language"]

--
// SEE ALSO SECTION ENDS
