---
title: "<<"
title_expanded: bitshift left
categories: [ "Structure" ]
subCategories: [ "Bitwise Operators" ]
---





= << Побітовий зсув вліво


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Оператор зсуву вліво `<<` призводить до зсуву бітів лівого операнда *вліво* на кількість позицій, визначену правим операндом.
[%hardbreaks]


[float]
=== Syntax
`variable << number_of_bits;`


[float]
=== Parameters
`variable`: Допустимі типи даних: `byte`, `int`, `long`. +
`number_of_bits`: число, що < = 32. Допустимі типи даних: `int`.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code

[source,arduino]
----
int a = 5;      // binary: 0000000000000101
int b = a << 3; // binary: 0000000000101000, or 40 in decimal
----
[%hardbreaks]

[float]
=== Notes and Warnings
Коли ви зсуваєте значення x на y бітів (x << y), крайні ліві y бітів x губляться, буквально зсуваючись у забуття:

[source,arduino]
----
int x = 5;  // binary: 0000000000000101
int y = 14;
int result = x << y;  // binary: 0100000000000000 - the first 1 in 101 was discarded
----

Якщо ви впевнені, що жодна з одиниць у значенні не виштовхується в небуття, простий спосіб сприйняття оператора зсуву вліво полягає в тому, що він множить лівий операнд на 2 у степені правого операнда. Наприклад, щоб генерувати степені двійки, можна скористатися такими виразами:

[source,arduino]
----
   Operation  Result
   ---------  ------
    1 <<  0      1
    1 <<  1      2
    1 <<  2      4
    1 <<  3      8
    ...
    1 <<  8    256
    1 <<  9    512
    1 << 10   1024
    ...
----

Наступний приклад можна використати для виведення значення отриманого байта в монітор порту, використовуючи оператор зсуву вліво для переміщення вздовж байта знизу (LSB) догори (MSB), і виведення його двійкового значення:

[source,arduino]
----
// Prints out Binary value (1 or 0) of byte
void printOut1(int c) {
  for (int bits = 7; bits > -1; bits--) {
    // Compare bits 7-0 in byte
    if (c & (1 << bits)) {
      Serial.print("1");
    }
    else {
      Serial.print("0");
    }
  }
}
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS




//SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== See also

[role="language"]

[role="example"]
* #EXAMPLE# https://www.arduino.cc/playground/Code/BitMath[BitMath Tutorial^]

--
//SEE ALSO SECTION ENDS

