---
title: "^"
title_expanded: bitwise xor
categories: [ "Structure" ]
subCategories: [ "Bitwise Operators" ]
---





= ^ Побітове XOR (ВИКЛЮЧНЕ АБО)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
У C++ є дещо незвичний оператор, який називається побітове ВИКЛЮЧНЕ АБО, також відоме як побітове XOR. (Англійською мовою він зазвичай вимовляється "екс-ор"). Оператор побітового XOR записується за допомогою символу каретки `^`. Побітова операція XOR повертає 1 тільки в тому випадку, якщо вхідні біти відрізняються, інакше повертає 0.
[%hardbreaks]

Точніше кажучи,

    0  0  1  1    operand1
    0  1  0  1    operand2
    ----------
    0  1  1  0    (operand1 ^ operand2) - returned result
[%hardbreaks]

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code

[source,arduino]
----
int x = 12;     // binary: 1100
int y = 10;     // binary: 1010
int z = x ^ y;  // binary: 0110, or decimal 6
----
[%hardbreaks]

Оператор ^ часто використовується для перемикання (тобто зміни з 0 на 1 або з 1 на 0) деяких бітів у цілочисельному виразі. У побітовій операції XOR, якщо в біті маски є 1, цей біт інвертується; якщо є 0, біт не інвертується і залишається незмінним.

[source,arduino]
----
// Note: This code uses registers specific to AVR microcontrollers (Uno, Nano, Leonardo, Mega, etc.)
// it will not compile for other architectures
void setup() {
  DDRB = DDRB | 0b00100000;  // set PB5 (pin 13 on Uno/Nano, pin 9 on Leonardo/Micro, pin 11 on Mega) as OUTPUT
  Serial.begin(9600);
}

void loop() {
  PORTB = PORTB ^ 0b00100000;  // invert PB5, leave others untouched
  delay(100);
}
----


--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="example"]
* #EXAMPLE# https://www.arduino.cc/playground/Code/BitMath[BitMath Tutorial^]

--
// SEE ALSO SECTION ENDS
