---
title: "="
title_expanded: "assignment operator"
categories: [ "Structure" ]
subCategories: [ "Arithmetic Operators" ]
---





= = Присвоювання (один знак дорівнює)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Один знак дорівнює `=` у мові програмування C++ називається оператором присвоювання. Він має інше значення, ніж на уроках алгебри, де він вказував на рівняння або рівність. Оператор присвоювання повідомляє мікроконтролеру, що потрібно обчислити будь-яке значення або вираз з правого боку від знака дорівнює і зберегти його в змінній ліворуч від знака дорівнює.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code



[source,arduino]
----
int sensVal;              // declare an integer variable named sensVal
sensVal = analogRead(0);  // store the (digitized) input voltage at analog pin 0 in SensVal
----
[%hardbreaks]

[float]
=== Notes and Warnings
1. Змінна з лівого боку від оператора присвоювання (знак = ) повинна мати можливість вмістити значення, збережене в ній. Якщо вона недостатньо велика для зберігання значення, значення, збережене в змінній, буде неправильним.

2. Не плутайте оператор присвоювання [ = ] (один знак дорівнює) з оператором порівняння [ == ] (подвійний знак дорівнює), який визначає, чи рівні два вирази.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS

// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE#  link:../../control-structure/if[if (conditional operators)]
* #LANGUAGE#  link:../../../variables/data-types/char[char]
* #LANGUAGE#  link:../../../variables/data-types/int[int]
* #LANGUAGE#  link:../../../variables/data-types/long[long]

--
// SEE ALSO SECTION ENDS
