---
title: HIGH | LOW
categories: [ "Variables" ]
subCategories: [ "Constants" ]
---

= HIGH | LOW

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
== Визначення рівнів на пінах: HIGH та LOW
При зчитуванні чи записі на цифровий пін існує лише два можливих значення, які пін може прийняти/бути встановленим: `HIGH` та `LOW`. Вони є тими ж самими, що й `true` та `false`, а також `1` та `0`.

[float]
=== HIGH
Значення `HIGH` (стосовно піна) дещо відрізняється залежно від того, чи пін встановлено як `INPUT` або `OUTPUT`. Коли пін налаштований як `INPUT` за допомогою `link:../../../functions/digital-io/pinmode[pinMode()]`, і зчитується за допомогою `link:../../../functions/digital-io/digitalread[digitalRead()]`, Arduino (ATmega) повідомить статус `HIGH`, якщо:

  - наявна напруга більша за 3.0В на піні (плати 5В)
  - наявна напруга більша за 2.0В на піні (плати 3.3В)
[%hardbreaks]

Пін також може бути налаштований як `INPUT` за допомогою функції link:../../../functions/digital-io/pinmode[`pinMode()`], а згодом на нього може бути подано рівень `HIGH` за допомогою функції `link:../../../functions/digital-io/digitalwrite[digitalWrite()]`. Це ввімкне внутрішні підтягувальні резистори 20КОм (pullup), які _підтягуватимуть_ вхідний пін до рівня `HIGH`, доки він не буде підтягнутий до `LOW` зовнішнім електричним колом. Це також можна зробити альтернативним способом, передавши аргумент `INPUT_PULLUP` до функції link:../../../functions/digital-io/pinmode[`pinMode()`], що детальніше пояснюється в розділі "Визначення режимів цифрових пінів: INPUT, INPUT_PULLUP та OUTPUT" нижче.
[%hardbreaks]

Коли пін налаштований як `OUTPUT` за допомогою link:../../../functions/digital-io/pinmode[`pinMode()`], і на ньому встановлено рівень `HIGH` за допомогою link:../../../functions/digital-io/digitalwrite[`digitalWrite()`], пін отримує:

  - 5 вольт (плати 5В)
  - 3.3 вольта (плати 3.3В)

У цьому стані він може слугувати джерелом струму (source current), наприклад, запалювати світлодіод, підключений через послідовний резистор до землі.
[%hardbreaks]

[float]
=== LOW

Значення `LOW` також має різний зміст залежно від того, чи пін встановлено як `INPUT` або `OUTPUT`. Коли пін налаштований як `INPUT` за допомогою `pinMode()`, і зчитується за допомогою `digitalRead()`, Arduino (ATmega) повідомить про статус `LOW`, якщо:

наявна напруга менша за 1.5В на піні (плати 5В)

наявна напруга менша за 1.0В (приблизно) на піні (плати 3.3В)

Коли пін налаштований як `OUTPUT` за допомогою `pinMode()`, і на ньому встановлено рівень `LOW` за допомогою `digitalWrite()`, пін отримує 0 вольт (для плат 5В та 3.3В). В цьому стані він може поглинати струм (sink current), наприклад, запалювати світлодіод, який підключений через послідовний резистор до +5 вольт (або +3.3 вольт).

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Пов'язані матеріали

[role="language"]

--
// SEE ALSO SECTION ENDS
