---
title: INPUT | INPUT_PULLUP | OUTPUT
categories: [ "Variables" ]
subCategories: [ "Constants" ]
---

= INPUT | INPUT_PULLUP | OUTPUT

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
== Визначення режимів цифрових пінів: INPUT, INPUT_PULLUP та OUTPUT
Цифрові піни можуть бути використані як `INPUT`, `INPUT_PULLUP` або `OUTPUT`. Зміна стану піна за допомогою link:../../../functions/digital-io/pinmode[`pinMode()`] змінює електричну поведінку піна.

--
// OVERVIEW SECTION ENDS

// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== INPUT
Піни Arduino (ATmega), налаштовані як `INPUT` за допомогою link:../../../functions/digital-io/pinmode[`pinMode()`], вважаються такими, що знаходяться у стані _високого імпедансу_ (high-impedance). Піни, налаштовані як `INPUT`, створюють надзвичайно малі вимоги до електричного кола, яке вони вимірюють, еквівалентно послідовному резистору 100 Мегаом перед піном. Це робить їх корисними для зчитування з датчиків.
[%hardbreaks]

Якщо ваш пін налаштований як `INPUT` і ви зчитуєте перемикач, то коли перемикач знаходиться у відкритому стані, вхідний пін буде "плаваючим" (floating), що призведе до непередбачуваних результатів. Щоб забезпечити коректне зчитування, коли перемикач відкритий, потрібно використовувати підтягувальний (pull-up) або стягувальний (pull-down) резистор. Метою цього резистора є підтягування піна до відомого стану, коли перемикач знаходиться у відкритому стані. Зазвичай вибирають резистор 10 кОм, оскільки його значення є достатньо низьким, щоб надійно запобігти плаваючому входу, і водночас достатньо високим, щоб не витрачати забагато струму при закритому перемикачі. Дивіться туторіал http://arduino.cc/en/Tutorial/DigitalReadSerial[Digital Read Serial^] для отримання додаткової інформації.
[%hardbreaks]

Якщо використовується стягувальний (pull-down) резистор, вхідний пін матиме рівень `LOW`, коли перемикач відкритий, і рівень `HIGH`, коли перемикач закритий.
[%hardbreaks]

Якщо використовується підтягувальний (pull-up) резистор, вхідний пін матиме рівень `HIGH`, коли перемикач відкритий, і рівень `LOW`, коли перемикач закритий.
[%hardbreaks]

[float]
=== INPUT_PULLUP
Мікроконтролер ATmega на платі Arduino має внутрішні підтягувальні резистори (резистори, що внутрішньо підключаються до живлення), до яких ви маєте доступ. Якщо ви віддаєте перевагу їх використанню замість зовнішніх підтягувальних резисторів, ви можете використовувати аргумент `INPUT_PULLUP` у функції link:../../../functions/digital-io/pinmode[`pinMode()`].
[%hardbreaks]

Дивіться туторіал http://arduino.cc/en/Tutorial/InputPullupSerial[Input Pullup Serial^] для прикладу практичного використання.
[%hardbreaks]

Піни, налаштовані як входи з використанням `INPUT` або `INPUT_PULLUP`, можуть бути пошкоджені або знищені, якщо вони підключені до напруг нижче рівня землі (негативних напруг) або вище шини позитивного живлення (5В або 3В).
[%hardbreaks]

[float]
=== OUTPUT
Піни, налаштовані як `OUTPUT` за допомогою link:../../../functions/digital-io/pinmode[`pinMode()`], вважаються такими, що знаходяться у стані _низького імпедансу_ (low-impedance). Це означає, що вони можуть постачати значну кількість струму до інших електричних кіл. Піни ATmega можуть слугувати джерелом струму або поглинати струм до 40 мА (міліампер) для інших пристроїв/кіл. Це робить їх корисними для живлення світлодіодів, оскільки світлодіоди зазвичай використовують менше 40 мА. Навантаження, які потребують більше 40 мА (наприклад, двигуни), будуть вимагати використання транзистора або іншої інтерфейсної схеми.
[%hardbreaks]

Піни, налаштовані як виходи, можуть бути пошкоджені або знищені, якщо вони підключені до землі або шин позитивного живлення.
[%hardbreaks]


--
// HOW TO USE SECTION ENDS



// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Пов'язані матеріали

[role="language"]

--
// SEE ALSO SECTION ENDS
