---
title: Integer Constants
categories: [ "Variables" ]
subCategories: [ "Constants" ]
---





= Integer Constants


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Опис
Цілочисельні константи — це числа, які безпосередньо використовуються в скетчі, наприклад 123. За замовчуванням ці числа розглядаються як link:../../data-types/int[int], але ви можете змінити це за допомогою модифікаторів U та L (дивіться нижче).
[%hardbreaks]

Зазвичай цілочисельні константи розглядаються як цілі числа за основою 10 (десяткові), але може використовуватись спеціальна нотація (форматери) для введення чисел в інших системах числення.
[%hardbreaks]

|===
|Основа |Приклад |Форматер |Коментар

|10 (десяткова)
|123
|немає
|

|2 (двійкова)
|0b1111011
|починається з "0b"
|символи 0 та 1 є дійсними

|8 (вісімкова)
|0173
|починається з "0"
|символи 0-7 є дійсними

|16 (шістнадцяткова)
|0x7B
|починається з "0x"
|символи 0-9, A-F, a-f є дійсними
|===
[%hardbreaks]

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--
[float]
== Десяткова (основа 10)
Це звичайна математика, з якою ви знайомі. Константи без інших префіксів вважаються у десятковому форматі.

[float]
=== Приклад коду:
[source,arduino]
----
n = 101;  // те саме, що 101 у десятковій системі ((1 * 10^2) + (0 * 10^1) + 1)
----
[%hardbreaks]

[float]
== Двійкова (основа 2)
Тільки символи 0 та 1 є дійсними.

[float]
=== Приклад коду:
[source,arduino]
----
n = 0b101; // те саме, що 5 у десятковій системі ((1 * 2^2) + (0 * 2^1) + 1)
----
[%hardbreaks]

[float]
== Вісімкова (основа 8)
Тільки символи від 0 до 7 є дійсними. Вісімкові значення вказуються префіксом "0" (нуль).

[float]
=== Приклад коду:
[source,arduino]
----
n = 0101; // те саме, що 65 у десятковій системі ((1 * 8^2) + (0 * 8^1) + 1)
----
Існує ймовірність (ненавмисно) створити важковловиму помилку (баг), додавши нуль перед константою на початку, через що компілятор ненавмисно інтерпретує вашу константу як вісімкову.
[%hardbreaks]

[float]
== Шістнадцяткова (основа 16)
Дійсні символи від 0 до 9 та літери від A до F; A має значення 10, B — 11, аж до F, яке становить 15. Шістнадцяткові значення вказуються префіксом "0x". Зверніть увагу, що A-F можуть бути великими (A-F) або малими літерами (a-f).

[float]
=== Приклад коду:
[source,arduino]
----
n = 0x101;  // те саме, що 257 у десятковій системі ((1 * 16^2) + (0 * 16^1) + 1)
----
[%hardbreaks]


[float]
=== Примітки та попередження
*Форматери U та L:*

За замовчуванням цілочисельна константа вважається типом int з відповідними обмеженнями значень. Щоб вказати цілочисельну константу з іншим типом даних, після неї допишіть:

  - 'u' або 'U', щоб перевести константу в формат беззнакових даних. Приклад: 33u
  - 'l' або 'L', щоб перевести константу у формат даних типу long. Приклад: 100000L
  - 'ul' або 'UL', щоб перевести константу в константу типу unsigned long. Приклад: 32767ul

[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== Пов'язані матеріали

[role="language"]

--
// SEE ALSO SECTION ENDS
