---
title: shiftIn()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---





= shiftIn()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Зчитує байт даних по одному біту за раз. Починає або з найбільш значущого (тобто крайнього лівого), або з найменш значущого (крайнього правого) біта. Для кожного біта на вивід синхронізації подається високий рівень, зчитується наступний біт з лінії даних, після чого на вивід синхронізації подається низький рівень.

Якщо ви взаємодієте з пристроєм, який тактується по передньому фронту, вам потрібно переконатися, що на виводі синхронізації встановлено низький рівень перед першим викликом `shiftIn()`, наприклад, викликом `digitalWrite(clockPin, LOW)`.

Примітка: це програмна реалізація; Arduino також надає link:https://www.arduino.cc/en/Reference/SPI[бібліотеку SPI], яка використовує апаратну реалізацію, що працює швидше, але лише на певних виводах.
[%hardbreaks]


[float]
=== Syntax
`byte incoming = shiftIn(dataPin, clockPin, bitOrder)`


[float]
=== Parameters
`dataPin`: вивід, з якого здійснюється ввід кожного біта. Дозволені типи даних: `int`. +
`clockPin`: вивід для перемикання стану, що сигналізує про зчитування з *dataPin*. +
`bitOrder`: порядок зчитування бітів; або *MSBFIRST*, або *LSBFIRST*. (Найбільш значущий біт першим, або Найменш значущий біт першим).


[float]
=== Returns
Зчитане значення. Тип даних: `byte`.

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

--
// SEE ALSO SECTION ENDS
