---
title: shiftOut()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---

= shiftOut()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Виводить байт даних по одному біту за раз. Починає або з найбільш значущого (тобто крайнього лівого), або з найменш значущого (крайнього правого) біта. Кожен біт по черзі записується на вивід даних, після чого на вивід синхронізації подається імпульс (встановлюється високий рівень, потім низький), щоб вказати, що біт доступний.

Примітка: якщо ви взаємодієте з пристроєм, який тактується по передньому фронту, вам потрібно переконатися, що на виводі синхронізації встановлено низький рівень перед викликом `shiftOut()`, наприклад, викликом `digitalWrite(clockPin, LOW)`.

Це програмна реалізація; дивіться також https://www.arduino.cc/en/Reference/SPI[бібліотеку SPI], яка надає апаратну реалізацію, що працює швидше, але лише на певних виводах.
[%hardbreaks]


[float]
=== Syntax
`shiftOut(dataPin, clockPin, bitOrder, value)`


[float]
=== Parameters
`dataPin`: вивід, на який виводиться кожен біт. Дозволені типи даних: `int`. +
`clockPin`: вивід для перемикання після того, як dataPin буде встановлено у відповідне значення. Дозволені типи даних: `int`. +
`bitOrder`: порядок виведення бітів; або MSBFIRST, або LSBFIRST. (Найбільш значущий біт першим, або Найменш значущий біт першим). +
`value`: дані для виведення. Дозволені типи даних: `byte`.


[float]
=== Returns
Нічого

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Example Code
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Для супровідної схеми див. https://arduino.cc/en/Tutorial/ShiftOut[посібник з керування зсувним регістром 74HC595].

[source,arduino]
----
//**************************************************************//
//  Name    : shiftOutCode, Hello World                         //
//  Author  : Carlyn Maw,Tom Igoe                               //
//  Date    : 25 Oct, 2006                                      //
//  Version : 1.0                                               //
//  Notes   : Code for using a 74HC595 Shift Register           //
//          : to count from 0 to 255                            //
//****************************************************************

//Pin connected to ST_CP of 74HC595
int latchPin = 8;
//Pin connected to SH_CP of 74HC595
int clockPin = 12;
////Pin connected to DS of 74HC595
int dataPin = 11;

void setup() {
  //set pins to output because they are addressed in the main loop
  pinMode(latchPin, OUTPUT);
  pinMode(clockPin, OUTPUT);
  pinMode(dataPin, OUTPUT);
}

void loop() {
  //count up routine
  for (int j = 0; j < 256; j++) {
    //ground latchPin and hold low for as long as you are transmitting
    digitalWrite(latchPin, LOW);
    shiftOut(dataPin, clockPin, LSBFIRST, j);
    //return the latch pin high to signal chip that it
    //no longer needs to listen for information
    digitalWrite(latchPin, HIGH);
    delay(1000);
  }
}
----
[%hardbreaks]

[float]
=== Notes and Warnings
Керуючі виводи dataPin та clockPin вже повинні бути налаштовані як виходи за допомогою виклику функції link:../../digital-io/pinmode[pinMode()].

shiftOut наразі написана для виведення 1 байта (8 бітів), тому для виведення значень більших за 255 потрібна двоетапна операція.
[source,arduino]
----
// Do this for MSBFIRST serial
int data = 500;
// shift out highbyte
shiftOut(dataPin, clock, MSBFIRST, (data >> 8));
// shift out lowbyte
shiftOut(dataPin, clock, MSBFIRST, data);

// Or do this for LSBFIRST serial
data = 500;
// shift out lowbyte
shiftOut(dataPin, clock, LSBFIRST, data);
// shift out highbyte
shiftOut(dataPin, clock, LSBFIRST, (data >> 8));
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

--
// SEE ALSO SECTION ENDS
